sudo: required
services:
    - docker

before_install:
    - docker build -t moath/react-test -f ./react-client/Dockerfile.dev ./react-client

script:
    - docker run moath/react-test npm test -- --coverage

after_success:
    - docker build -t moath/multi-nginx ./nginx
    - docker build -t moath/multi-worker ./worker
    - docker build -t moath/multi-client ./react-client
    - docker build -t moath/multi-server ./express-server
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push images to docker hub
    - docker push moath/multi-nginx 
    - docker push moath/multi-worker
    - docker push moath/multi-client
    - docker push moath/multi-server

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-564950470946
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
