version: "3"
services:

    nginx: 
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - '80:80'
    postgres:
        image: 'postgres:latest'

    redis:
        image: 'redis:latest'

    express-server:
        build:
            context: ./express-server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./express-server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379

            - PGHOST=postgres
            - PGUSER=postgres
            - PGPORT=5432
            - PGPASSWORD=postgres_password
            - PGDATABASE=postgres

    react-client:
        build:
            context: ./react-client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./react-client:/app

    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379

